### ISSUE TITLE
React.js bug: Fix parsing error

### ISSUE THREAD

**Issue by Hestben** [duckduckgo/zeroclickinfo-fathead#772]
### Description
Currently running parse.sh results in an error:
`Traceback (most recent call last):
  File "parse.py", line 189, in <module>
    parsed_api_docs.parse_data(file_data)
  File "parse.py", line 77, in parse_data
    content = self.parse_content(api)
  File "parse.py", line 114, in parse_content
    if tag.name == 'hr' or tag.name == 'blockquote':
  File "/usr/lib/python2.7/dist-packages/bs4/element.py", line 669, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'NavigableString' object has no attribute 'name'`
This is probably due to some change in the doc format.

## People to notify

@pjhampton 

---

Instant Answer Page: https://duck.co/ia/view/reactjs

**Comment by Hestben** [comment]
And I would like to assign myself.
